#!/bin/bash
clear
s="session_placeholder"
v="version_placeholder"
destination="destination_placeholder"
days="days_placeholder"
echo "Server Backup Script"
echo "Name: $s"
echo "Minecraft Version: $v"
./stop_server
sleep 1
find ../${destination} -mtime +${days} -type d -exec rm -r {} \;
date="$(date +"%d-%m-%Y")"
mkdir ../${destination}/${date}
cp -r * ../${destination}/${date}