#!/bin/bash
clear
s="session_placeholder"
v="version_placeholder"
destination="destination_placeholder"
days="14"
echo "Server Backup Script"
echo "Name: $s"
echo "Minecraft Version: $v"
./scripts/stop_server
sleep 45
find ../${destination} -mtime +${days} -type d -exec rm -r {} \;
date="$(date +"%d-%m-%Y")"
rand=""
rand+="-"
rand+="$RANDOM"
mkdir ../../${destination}/${date}/${rand}
cp -r * ../../${destination}/${date}/${rand}
echo "Server Backup Complete."