#!/bin/bash
clear
s="session_placeholder"
v="version_placeholder"
destination="destination_placeholder"
echo "Server Backup Script"
echo "Name: $s"
echo "Minecraft Version: $v"
tmux has-session -t $s 2>/dev/null
if [ $? != 0 ]; then
  echo "ERROR! -- Server Not Running!"
  exit
fi
tmux send-keys -t $s 'stop' C-m
tmux attach -t $s
echo "$v Server Shutdown"
sleep 45
find ../../${destination} -mtime +14 -type d -exec rm -r {} \;
date="$(date +"%d-%m-%Y")"
rand=""
rand+="-"
rand+="$RANDOM"
mkdir ../../${destination}/${date}${rand}
cp -r ../ ../../${destination}/${date}${rand}
echo "Server Backup Complete."
echo "Starting Server"
cd ..
./scripts/start_server