#!/bin/bash
clear
s="session_placeholder"
v="version_placeholder"
destination="destination_placeholder"
days="14"
echo "Server Backup Script"
echo "Name: $s"
echo "Minecraft Version: $v"
./stop_server
sleep 45
find ../../${destination} -mtime +${days} -type d -exec rm -r {} \;
date="$(date +"%d-%m-%Y")"
mkdir ../../${destination}/${date}
cp -r * ../../${destination}/${date}
echo "Server Backup Complete."
echo "Starting Server"
./start_server